name: Build & Push to Cloudsmith

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write   # Required for requesting the OIDC JWT
  contents: read     # Required for actions/checkout

env:
  CLOUDSMITH_WORKSPACE: red-acme-inc
  CLOUDSMITH_REPO: cldsmth-overview
  CLOUDSMITH_SERVICE: gh-actions-3vjo # The service slug for the Cloudsmith service
  DOCKER_REGISTRY: docker.cloudsmith.io/red-acme-inc/cldsmth-overview

jobs:
  build-python-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v2.0.2
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_WORKSPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE }}
          oidc-auth-only: 'true'

      - name: Log in to Cloudsmith Docker Registry
        run: |
          echo "${{ env.CLOUDSMITH_API_KEY }}" | \
            docker login docker.cloudsmith.io \
              -u "token" \
              --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          provenance: false
          push: true
          tags: docker.cloudsmith.io/${{ env.CLOUDSMITH_WORKSPACE }}/${{ env.CLOUDSMITH_REPOSITORY }}/python-app:${{github.run_number}}
          build-args: |
            CLOUDSMITH_SERVICE=${{ env.CLOUDSMITH_SERVICE }}
            CLOUDSMITH_WORKSPACE=${{ env.CLOUDSMITH_WORKSPACE }}
            CLOUDSMITH_REPOSITORY=${{ env.CLOUDSMITH_REPOSITORY }}
            CLOUDSMITH_API_KEY=${{ env.CLOUDSMITH_API_KEY }}
            BUILDKIT_PROGRESS=plain
            
#      - name: Build Python API image
#        run: |
#          docker build \
#            --build-arg CLOUDSMITH_API_KEY=${{ env.CLOUDSMITH_API_KEY }} \
#            -t ${{ env.DOCKER_REGISTRY }}/python-api:${{ github.sha }} \
#            -t ${{ env.DOCKER_REGISTRY }}/python-api:latest \
#            ./services/python-api
#
#      - name: Push Python API image
#        if: github.ref == 'refs/heads/main'
#        run: |
#          docker push ${{ env.DOCKER_REGISTRY }}/python-api:${{ github.sha }}
#          docker push ${{ env.DOCKER_REGISTRY }}/python-api:latest

  build-node-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v2.0.2
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_WORKSPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE }}
          oidc-auth-only: 'true'

      - name: Log in to Cloudsmith Docker Registry
        run: |
          echo "${{ env.CLOUDSMITH_API_KEY }} | \
            docker login docker.cloudsmith.io \
              -u "token" \
              --password-stdin

      - name: Build Node Web image
        run: |
          docker build \
            --build-arg CLOUDSMITH_API_KEY=${{ env.CLOUDSMITH_API_KEY }} \
            -t ${{ env.DOCKER_REGISTRY }}/node-web:${{ github.sha }} \
            -t ${{ env.DOCKER_REGISTRY }}/node-web:latest \
            ./services/node-web

      - name: Push Node Web image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/node-web:${{ github.sha }}
          docker push ${{ env.DOCKER_REGISTRY }}/node-web:latest
